"""initial schema

Revision ID: 00b8cbe57ea7
Revises: 
Create Date: 2025-07-03 12:12:21.006415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b8cbe57ea7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('investor_profile', sa.JSON(), nullable=True),
    sa.Column('watchlist_symbols', sa.JSON(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
